@DynamicProxy_HostAddress = http://localhost:5108

POST {{DynamicProxy_HostAddress}}/proxymanagnent?endpointName=test&forwardTo=http://wp.pl
Accept: application/json
###
GET {{DynamicProxy_HostAddress}}/proxymanagnent?key=test
Accept: application/json
###
GET {{DynamicProxy_HostAddress}}/test/463
Accept: application/json
###