@DynamicProxy_HostAddress = http://localhost:5108

POST {{DynamicProxy_HostAddress}}/proxymanagnent?endpointName=loc&forwardTo=80
Accept: application/json
###
GET {{DynamicProxy_HostAddress}}/proxymanagnent?key=test
Accept: application/json
###
GET {{DynamicProxy_HostAddress}}/loc/srfdygdretf
Accept: application/json
###